languageCode = "en"
title = "Abdias river"
baseURL = "https://axeso.red/"
enableRobotsTXT = true
theme = "avi-go"
disableHugoGeneratorInject = true
PygmentsCodeFences = true
PygmentsUseClasses = true
#DisqusShortname = ""
#SectionPagesMenu = "main"


[params]
  description = "Axeso en la red."
  author = "Abdiasriver"
  images = ["/images/bg-image.jpg"]


[[menu.main]]
    url = "/Blog/"
    name = "Blog"
    weight = 1

[[menu.main]]
    url = "/categories/"
    name = "Categories"
    weight = 2

[[menu.icon]]
    url = "mailto:root@axeso.red"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/abdiasriver/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/abdiasriver/"
    name = "twitter"
    weight = 3

[permalinks]
  post = "/:title/"
  blog = "/:title/"
  linux = "/:title/"
  windows = "/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  lego = "lego"
